# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1FVFUjQIP8XjsySothv6cEC3kjs8q-2
"""

from google.colab import drive
drive.mount('/content/drive')
import zipfile
import os

base_path = "/content/dataset"
os.makedirs(base_path, exist_ok=True)

# Change path if your files are inside a folder
train_zip = "/content/drive/MyDrive/train.zip"
val_zip = "/content/drive/MyDrive/validation.zip"
test_zip = "/content/drive/MyDrive/test.zip"

# Extract train
with zipfile.ZipFile(train_zip, 'r') as zip_ref:
    zip_ref.extractall(base_path)

# Extract validation
with zipfile.ZipFile(val_zip, 'r') as zip_ref:
    zip_ref.extractall(base_path)

# Extract test
with zipfile.ZipFile(test_zip, 'r') as zip_ref:
    zip_ref.extractall(base_path)
import os
print(os.listdir('/content/dataset'))

import shutil
shutil.rmtree('/content/dataset')
import zipfile
import os

base_path = "/content/dataset"

os.makedirs(base_path + "/train", exist_ok=True)
os.makedirs(base_path + "/validation", exist_ok=True)
os.makedirs(base_path + "/test", exist_ok=True)

with zipfile.ZipFile('/content/drive/MyDrive/train.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/train")

with zipfile.ZipFile('/content/drive/MyDrive/validation.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/validation")

with zipfile.ZipFile('/content/drive/MyDrive/test.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/test")
import os
print(os.listdir('/content/dataset'))

from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive
!mkdir /content/dataset
import zipfile

# Train
with zipfile.ZipFile('/content/drive/MyDrive/train.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset/train')

# Validation
with zipfile.ZipFile('/content/drive/MyDrive/validation.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset/validation')

# Test
with zipfile.ZipFile('/content/drive/MyDrive/test.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset/test')
!ls /content/dataset
!ls /content/dataset/train

import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/dataset/train",
    image_size=(224, 224),
    batch_size=32
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/dataset/validation",
    image_size=(224, 224),
    batch_size=32
)

class_names = train_ds.class_names
print(class_names)

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(224, 224, 3)),

    layers.Conv2D(32, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(len(class_names), activation='softmax')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15
)

model.save('/content/drive/MyDrive/fruit_model.keras')
    
from google.colab import drive
drive.mount('/content/drive')
import os
import zipfile

base_path = "/content/dataset"

os.makedirs(base_path + "/train", exist_ok=True)
os.makedirs(base_path + "/validation", exist_ok=True)
os.makedirs(base_path + "/test", exist_ok=True)
with zipfile.ZipFile('/content/drive/MyDrive/train.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/train")

with zipfile.ZipFile('/content/drive/MyDrive/validation.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/validation")

with zipfile.ZipFile('/content/drive/MyDrive/test.zip', 'r') as zip_ref:
    zip_ref.extractall(base_path + "/test")
    import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/dataset/train",
    image_size=(224, 224),
    batch_size=32
)

class_names = train_ds.class_names
print(class_names)
from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/fruit_model.keras')

from google.colab import files
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import numpy as np

uploaded = files.upload()

img_path = list(uploaded.keys())[0]

# Show image
img_display = image.load_img(img_path)
plt.imshow(img_display)
plt.axis('off')

# Process image
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

# Predict
# categories
fruit_classes = ['apple','banana','grapes','mango','orange','watermelon','kiwi','lemon','pear','pineapple','pomegranate']
vegetable_classes = ['beetroot','bell pepper','carrot','cabbage','capsicum','cauliflower','chili pepper','corn','eggplant','lettuce','potato','tomato','onion','cucumber','radish','spinach','sweet potato']
spices_classes = ['garlic','ginger','jalapeno','paprika']
legumes_classes = ['peas','soy beans']
threshold = 0.75
prediction = model.predict(img_array)
predicted_class = class_names[np.argmax(prediction)]
confidence = np.max(prediction)

# UNKNOWN detection
if confidence < threshold:
   title = f"Unknown Item ❌\nConfidence: {confidence*100:.2f}%"

else:
    if predicted_class in fruit_classes:
        category = "FRUIT"
    elif predicted_class in vegetable_classes:
        category = "VEGETABLE"
    elif predicted_class in spices_classes:
        category = "SPICES"
    elif predicted_class in legumes_classes:
        category = "LEGUMES"
    else:
        category = "OTHER"

    title = f"{category}\n{predicted_class} ({confidence*100:.2f}%)"

# Show result
plt.imshow(img_display)
plt.title(title)
plt.axis('off')
plt.show()

#  Unknown detection
threshold = 0.75

if confidence < threshold:
    print("Unknown Image ")
    print(f"Confidence: {confidence*100:.2f}%")
else:
  # Show result
    print(f"Predicted: {predicted_class}")
    print(f"Confidence: {confidence*100:.2f}%")
